### PR TITLE
fix: error TS6137: Cannot import type declaration files. Consider importing 'express' instead of '@types/express'

### PR DESCRIPTION
**Pull request by smoke**
for more info see https://github.com/Microsoft/TypeScript/issues/16472

### CODE REVIEW

**Comment by tinganho** [comment]
Is there any compile errors with the current solution? It seems like the issue you are referring to, suggests it's done correctly today, https://github.com/Microsoft/TypeScript/issues/16472#issuecomment-308255064.

**Comment by smoke** [comment]
With the newer version of TypeScript => 2.4.1 there is the pointed error.
I have referenced the issue as there, they have described that importing types directly is an error, instead packages from which types are used should be imported.
https://github.com/Microsoft/TypeScript/issues/16472#issuecomment-311524892

**Comment by tinganho** [comment]
~~But your change imports types directly no?~~

Sorry, I didn't look at the diff correctly. But you are right.

**Comment by tinganho** [comment]
Thanks @smoke !

**Comment by tinganho** [comment]
Published now on NPM express-request-language@1.1.12

**Pull request merged**
